Fixed error message in posinst

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -19,7 +19,7 @@ case "$1" in
 			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${DEFAULT_DISCOVER_METADATA_FILE}.diverted ${DEFAULT_DISCOVER_METADATA_FILE} ; then
 				ln -fs ${DISCOVER_METADATA_FILE_LLIUREX} ${DEFAULT_DISCOVER_METADATA_FILE}
    			else
-   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
+   				echo "Unable to divert file \"$DEFAULT_DISCOVER_AUTOSTART\"" >&2
 			fi
 		fi
 
@@ -27,7 +27,7 @@ case "$1" in
 			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${DEFAULT_DISCOVER_METADATA_JSON}.diverted ${DEFAULT_DISCOVER_METADATA_JSON} ; then
 				ln -fs ${DISCOVER_METADATA_JSON_LLIUREX} ${DEFAULT_DISCOVER_METADATA_JSON}
    			else
-   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
+   				echo "Unable to divert file \"$DEFAULT_DISCOVER_AUTOSTART\"" >&2
 			fi
 		fi	
 
