Fixed improved

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,7 +4,10 @@ set -e
 
 #VARS
 DEFAULT_DISCOVER_METADATA_FILE="/usr/share/plasma/plasmoids/org.kde.discovernotifier/metadata.desktop"
+DEFAULT_DISCOVER_METADATA_JSON="/usr/share/plasma/plasmoids/org.kde.discovernotifier/metadata.json"
 DISCOVER_METADATA_FILE_LLIUREX="/usr/share/lliurex-disable-discover-indicator/llx-discovernotifier-metadata.desktop"
+DISCOVER_METADATA_JSON_LLIUREX="/usr/share/lliurex-disable-discover-indicator/llx-discovernotifier-metadata.json"
+
 PACKAGE_NAME="lliurex-disable-discover-indicator"
 
 case "$1" in
@@ -12,6 +15,14 @@ case "$1" in
 		if [ -f $DEFAULT_DISCOVER_METADATA_FILE ];then
 			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${DEFAULT_DISCOVER_METADATA_FILE}.diverted ${DEFAULT_DISCOVER_METADATA_FILE} ; then
 				ln -fs ${DISCOVER_METADATA_FILE_LLIUREX} ${DEFAULT_DISCOVER_METADATA_FILE}
+   			else
+   				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
+			fi
+		fi
+
+		if [ -f $DEFAULT_DISCOVER_METADATA_JSON ];then
+			if dpkg-divert --package ${PACKAGE_NAME} --add  --rename  --divert ${DEFAULT_DISCOVER_METADATA_JSON}.diverted ${DEFAULT_DISCOVER_METADATA_JSON} ; then
+				ln -fs ${DISCOVER_METADATA_JSON_LLIUREX} ${DEFAULT_DISCOVER_METADATA_JSON}
    			else
    				echo "Unable to divert file \"$SWING_FILE_OPENJDK8\"" >&2
 			fi
